#+Title: Final Reserach Report P363 (Group 3)
#+Author: 

#+latex: \bibliographystyle{apalike}
#+latex: \bibliography{references}

* Introduction 

The use of experimental tests have been employed in Psychology ever since it was born. Ever since then there have been the development of a number of psychological tests to measure certain variables. One particular test that has been developed uses implicit attitudes to measure a person's underlying automatic evalutation on a certain subject, this is known as the Implicit Association Test (IAT) \cite{greenwald_mcghee_schwartz_1998}. This test works by displaying target words or images on screen and having participants respond to pairs of attitude objects (e.g. self vs other) or affective concepts (e.g. positive vs negative) by pressing a left versus right response key. The reaction time to attribute the response to the target object is then taken as an indicator of implicit attitudes. Past researchers have used this method to test a variety of implicit attitudes, such as attitudes towards one parent \cite{Yang_2013} or the subjective well-being of oneself \cite{Walker_Schimmack_2008}. More notably IAT measures are often used as self-esteem measures using words to describe a person's chracteristic and measuring how fast one responds to characteristics that they might attribute to themself. Taking inspiration from the study done by Karpinski (2004) we will adopt a similar format using a word bank of describing characterisitcs to measure implicit attitudes towards self-esteem. 
