#+Title: Final Reserach Report P363 (Group 3)
#+Author: 

#+latex: \bibliographystyle{apalike}
#+latex: \bibliography{references}

* Introduction 


The use of experimental tests have been employed in Psychology ever since it was born. Ever since then there have been the development of a number of psychological tests to measure certain variables. One particular test that has been developed uses implicit attitudes to measure a person's underlying automatic evalutation on a certain subject, this is known as the Implicit Association Test (IAT) \cite{greenwald_mcghee_schwartz_1998}. This test works by displaying target words or images on screen and having participants respond to pairs of attitude objects (e.g. self vs other) or affective concepts (e.g. positive vs negative) by pressing a left versus right response key. The reaction time to attribute the response to the target object is then taken as an indicator of implicit attitudes. Past researchers have used this method to test a variety of implicit attitudes, such as attitudes towards one parent \cite{Yang_2013} or the subjective well-being of oneself \cite{Walker_Schimmack_2008}. More notably IAT measures are often used as self-esteem measures using words to describe a person's chracteristic and measuring how fast one responds to characteristics that they might attribute to themself. Taking inspiration from the study done by Karpinski (2004) we will adopt a similar format using a word bank of describing characterisitcs to measure implicit attitudes towards self-esteem. 

* Method 

*Subjects*

Students from group 3 of Computing and Psychological Research course at University of Waterloo and their respective family members and friends participated in the study. The study consists of 5 students, XXX

#add study sample table consisting # of male and female subjects 

*Procedure*

In the IAT, the subject responds to a series of items that are to be clssssified in X categories, one assessing the associations of self versus other and the othe representing an attribute discriminatopn such as pleasent verus unplessent words. The experiment consisted of X blocks of categorization trials. The computer recorded the elapsed time between beginning of presentiation of each stimuls and occurence of keyboard response. 

The self-esteem IAT involves 5 steps *(#change the # depending on what we decide)*. In each step, the subject presses a left or right key to categorize each stimuli which are presented on the desktop screen. In the first step, the subjects practice a target concept by classifying items into self and other categories. In the second step, subjects practice an attriubte discrimination by assorting items in pleasent and unpleaent categories. *add further steps depending on our discussion*

*Results*
=======
  The use of experimental tests have been employed in Psychology ever since it was born. Ever since then there have been the development of a number of psychological tests to measure certain variables. One particular test that has been developed uses implicit attitudes to measure a person's underlying automatic evalutation on a certain subject, this is known as the Implicit Association Test (IAT) \cite{greenwald_mcghee_schwartz_1998}. This test works by displaying target words or images on screen and having participants respond to pairs of attitude objects (e.g. self vs other) or affective concepts (e.g. positive vs negative) by pressing a left versus right response key. The reaction time to attribute the response to the target object is then taken as an indicator of implicit attitudes. Past researchers have used this method to test a variety of implicit attitudes, such as attitudes towards one parent \cite{Yang_2013} or the subjective well-being of oneself \cite{Walker_Schimmack_2008}. More notably IAT measures are often used as self-esteem measures using words to describe a person's chracteristic and measuring how fast one responds to characteristics that they might attribute to themself. Taking inspiration from the study done by Karpinski (2004) we will adopt a similar format using a word bank of describing characterisitcs to measure implicit attitudes towards self-esteem. 
